version: '2'

services:
        proxy:
              image: traefik
              command: --web --web.address=:8686 --docker --docker.domain=docker.localhost --docker.watch --logLevel=DEBUG --entryPoints='Name:http Address::80' --defaultEntryPoints='http' --accessLogsFile='log/access.log'
              networks:
                        - "80:80"
                        - "8686:8686"
                        - "443:443"
              volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /home/thomas/traefik/traefik.toml:/traefik.toml

networks:
        webgateway:
                driver: bridge


                