version: '2'

services:
        traefik:
              image: traefik
              restart: always
              networks:
                        - web
              ports:
                        - "80:80"
                        - "8686:8686"
                        - "443:443"
              volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /opt/appdata/traefik/traefik.toml:/traefik.toml
                        - /opt/appdata/traefik/acme.json:/acme.json
              container_name: traefik

networks:
        web:
            external: true
                